In [6]:
import numpy as np

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$



In [ ]:
[1,1,-1,-2, 0],
[2,1,-1, 1,-2],
[1,1,-3, 1, 4]

[2, 2,-2,-4, 0],
[0,-1,-3,-3,-2],
[1, 1,-3, 1, 4]

[1, 1,-1,-2, 0],
[0,-1,-3,-3,-2],
[0, 0,-2, 3, 4]

Ранг матрицы равен максимальному порядку ненулевого минора.

Определитель для матрицы 3*3
Определитель = 2+0+0-0-0-0=2     
Определитель = -3-1-2+1+1+6=2   
Определитель = -9 +0+4-0-6-3 = -14

Определитель для расширенной матрицы 3*3
Определитель = -12 -8 +0 -0 -6-24 = -50

ранг - 3
ранг расширенной матрицы - 3

Кол-во переменных больше кол-ва уравнений. Система имеет бесконечное множество решений.

Решение в общем виде
x4 = c

-2*x3 + 4*c = 4
x3 = 2*c - 2

-x2-3*(2*c -2)-3*c = -2
x2 = 2 - 3*c - 6*c + 6
x2 = 8-9*c

x + 8 - 9*c - 2*c +2 - 4*c +4 = 0
x = 15*c - 14

Общее решение: 
    x = 15*c - 14
    x2 = 8-9*c
    x3 = 2*c - 2
    x4 = c

Частное решение:
    x = - 14
    x2 = 8
    x3 = - 2
    x4 = 0
    




In [16]:
# Проверка
a = np.array([[1.,1.,-1.,-2.],
              [2.,1.,-1., 1.],
              [1.,1.,-3., 1.]])
b =  np.array([[1,1,-1,-2, 0],
               [2,1,-1, 1,-2],
               [1,1,-3, 1, 4]])
print(f'Матрица:\n{a}')
r1 = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r1}')

print(f'Матрица:\n{b}')
r2 = np.linalg.matrix_rank(b)
print(f'Ранг матрицы: {r2}')

Матрица:
[[ 1.  1. -1. -2.]
 [ 2.  1. -1.  1.]
 [ 1.  1. -3.  1.]]
Ранг матрицы: 3
Матрица:
[[ 1  1 -1 -2  0]
 [ 2  1 -1  1 -2]
 [ 1  1 -3  1  4]]
Ранг матрицы: 3


In [19]:
v = np.array([0,-2.,4.])
x = np.linalg.solve(a,b)
# Ошибка из-за бесконечного множества решений?

LinAlgError: Last 2 dimensions of the array must be square

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$



In [22]:
#a) Ранги равны кол-ву переменных. Решение одно.

a = np.array([[3,-1,1],
              [2,-5,-3],
              [1,1,-1]])
b = np.array([[3,-1,1,4],
              [2,-5,-3,-17],
              [1,1,-1,0]])
v = np.array([4,-17,0])

print(f'Матрица:\n{a}')
r1 = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r1}')

print(f'Матрица:\n{b}')
r2 = np.linalg.matrix_rank(b)
print(f'Ранг матрицы: {r2}')

x = np.linalg.solve(a,v)
print(f'Решение: {x}')



Матрица:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Ранг матрицы: 3
Матрица:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг матрицы: 3
Решение: [1. 2. 3.]


In [23]:
#б) Ранги не равны и меньше кол-ва переменных. Решения нет.

a = np.array([[2,-4,6],
              [1,-2,3],
              [3,-6,9]])
b = np.array([[2,-4,6,1],
              [1,-2,3,-2],
              [3,-6,9,5]])
v = np.array([1,-2,5])

print(f'Матрица:\n{a}')
r1 = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r1}')

print(f'Матрица:\n{b}')
r2 = np.linalg.matrix_rank(b)
print(f'Ранг матрицы: {r2}')

x = np.linalg.solve(a,v)
print(f'Решение: {x}')




Матрица:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Ранг матрицы: 1
Матрица:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг матрицы: 2


LinAlgError: Singular matrix

In [24]:
#в) Ранги равны и меньше кол-ва переменных. Решений бесконечное множество.

a = np.array([[1,2,5],
              [3,1,-8]])
b = np.array([[1,2,5,4],
              [3,1,-8,-2]])
v = np.array([4,-2])

print(f'Матрица:\n{a}')
r1 = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r1}')

print(f'Матрица:\n{b}')
r2 = np.linalg.matrix_rank(b)
print(f'Ранг матрицы: {r2}')

x = np.linalg.solve(a,v)
print(f'Решение: {x}')



Матрица:
[[ 1  2  5]
 [ 3  1 -8]]
Ранг матрицы: 2
Матрица:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг матрицы: 2


LinAlgError: Last 2 dimensions of the array must be square

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [26]:
# Система совместна, имеет одно решение, т.к. ранги (размерность) равны кол-ву переменных.
a = np.array([[1,3,-2,4],
              [0,5,0,1],
              [0,0,-3,0],
              [0,0,0,2]])
b = np.array([[1,3,-2,4,3],
              [0,5,0,1,2],
              [0,0,-3,0,4],
              [0,0,0,2,1]])
v = np.array([3,2,4,1])

print(f'Матрица:\n{a}')
r1 = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r1}')

print(f'Матрица:\n{b}')
r2 = np.linalg.matrix_rank(b)
print(f'Ранг матрицы: {r2}')

x = np.linalg.solve(a,v)
print(f'Решение: {x}')




Матрица:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0 -3  0]
 [ 0  0  0  2]]
Ранг матрицы: 4
Матрица:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0 -3  0  4]
 [ 0  0  0  2  1]]
Ранг матрицы: 4
Решение: [-2.56666667  0.3        -1.33333333  0.5       ]


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [ ]:
[[1,2,3,a],
 [4,5,6,b],
 [7,8,9,c]]

[[1, 2, 3,   a],
 [0,-3,-6, b-4a],
 [0,-6,-12,c-7a]]

[[1, 2, 3,   a],
 [0,-3,-6, b-4a],
 [0, 0,0,c-7a+2b-8a]]

[[1, 2, 3,   a],
 [0,-3,-6, b-4a],
 [0, 0,0,c+2b-15a]]

В несовместной системе вектор (a,b,c) не принадлежит пространству, заданному матрицей.

При соотношении параметров c, 2b, -15a мы потеряем третью строку, система будет недоопределённой.
Ранг матрицы = 2 
Если c+2b-15a != 0 то система будет несовместной, не будет иметь решений.


In [28]:
a = np.array([[1, 2, 3],
             [0,-3,-6],
             [0, 0,0]])
print(f'Матрица:\n{a}')
r1 = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r1}')

b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(f'Матрица:\n{b}')
r1 = np.linalg.matrix_rank(b)
print(f'Ранг матрицы: {r1}')

Матрица:
[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]
Ранг матрицы: 2
Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы: 2


__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$





In [ ]:
а)
Определитель -4+6 = 2. Система имеет одно решение.
x1 = (-4+14)/2 = 5
x2 = (7-3)/2 = 2

проверка 5-4=1

In [ ]:
б) 
Определитель = 43 Система имеет одно решение.

x1 = 86/43 = 2
x2 = -43/43 = -1
x3 = 43/43 = 1

In [32]:
a = np.array([[2, -1, 5],
             [1,1,-3],
             [2, 4,1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

x1 = np.array([[10, -1, 5],
             [-2,1,-3],
             [1, 4,1]])
#print(f'Матрица:\n{a}')
print(f'Определитель x1:\n{np.linalg.det(x1):.0f}')

x2 = np.array([[2, 10, 5],
             [1,-2,-3],
             [2, 1,1]])
#print(f'Матрица:\n{a}')
print(f'Определитель x2:\n{np.linalg.det(x2):.0f}')

x3 = np.array([[2, -1, 10],
             [1,1,-2],
             [2, 4,1]])
#print(f'Матрица:\n{a}')
print(f'Определитель x3:\n{np.linalg.det(x3):.0f}')






Матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
43
Определитель x1:
86
Определитель x2:
-43
Определитель x3:
43


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    


__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$



__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.