Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [30]:
import numpy as np

1

а) Произведение AB и BA невозможно

б) Возможно произведение AB. Результирующая размерность 5*5

в) Возможно произведение AB и BA. В первом случае порядок квадратной матрицы 3, во втором - 8

г) Возможно произведение AB и BA. В обоих случаях порядок квадратной матрицы 4




In [31]:
# 2

# А + В = [[1+4, -2-1], [3, 5]] = [[5, -3], [3, 5]]

A = np.array([[1, -2], 
              [3, 0]])
B = np.array([[4, -1], 
              [0, 5]])
print(A+B)

# A * B = [[1*4-2*0, -1-10], [12+0, -3+0]] = [[-4, 11], [12, -3]]
print(np.dot(A,B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


In [32]:
# 3

# 3𝐴−2𝐵+4𝐶 = [[3, 21], [9, -18]] + [[0, -10],[-4, 2]] +[[8, -16],[4, 4]]=
# = [[11,-5],[9,-12]]
A = np.array([[1, 7], 
              [3, -6]])
B = np.array([[0, 5], 
              [2, -1]])
C = np.array([[2, -4], 
              [1, 1]])
3*𝐴-2*𝐵+4*𝐶 

array([[ 11,  -5],
       [  9, -12]])

In [33]:
# 4
# A*AT = [[4, 1], [5, -2], [2,3]] * [[4,5,2], [1,-2,3]] = 
#      = [[16+1,20-2,8+3],[20-2,25+4,10-6],[8+3,10-6,4+9]]

#      = [[17,18,11],[18,29,4],[11,4,11]]



# AT*A = [[4,5,2], [1,-2,3] * [4, 1], [5, -2], [2,3]] = 
#      = [[16+25+4,4-10+6],[4-10+6,1+4+9]] = 

#      = [[45,0],[0,14]]


A = np.array([[4, 1], 
              [5, -2],
              [2,3]])
print(A)
print(A.T)

print(np.dot(A,A.T))
print(np.dot(A.T,A))

[[ 4  1]
 [ 5 -2]
 [ 2  3]]
[[ 4  5  2]
 [ 1 -2  3]]
[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


In [34]:
# 5* Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [37]:
#1
# a) 𝑠𝑖𝑛𝑥 * 𝑠𝑖𝑛𝑥 + 𝑐𝑜𝑠𝑥 * 𝑐𝑜𝑠𝑥 = sin^2(x) + cos^2(x) = 1
# б) 4*5*9 = 180 или 9*|[4,2][0,5| = 9*(4*5-0*3) = 180
# в) 3*((4*8-5*7)-2*(8-2*7)+3*(5-8)) = 3*(-9+12-3) = 0

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


In [40]:
#2 det(A) = |4|
# a) det(A**2) = |16|
# б) det(AT) = |4|
# в) det(2A) = |8|



In [42]:
#3 Матрица называется _сингулярной_, или _вырожденной_, если ее определитель равен нулю.

# 7*((4*13+3*6)+2(-2*13 - 9)+(12+12)) = 7*(52+18-52-18) = 0

a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Ранг матрицы: 2


In [44]:
#4

# а) Третью строку можно отбросить. Ранг = 2
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{a}')
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r}')

# б) Ранг не больше 4, не меньше 1.
# По минору 2-го порядка |[4,3],[5,6]| ранг не меньше 2
# 1я строка + 2я строка = 3я строка - её можно отбросить. Ранг не больше 3.
# Дальнейшие линейные преобразования не получаются.
# Ответ:  3

b = np.array([[0, 0, 2,1], [0, 0, 2,2], [0, 0, 4,3],[2, 3, 5,6]])
print(f'Матрица:\n{b}')
r1 = np.linalg.matrix_rank(b)
print(f'Ранг матрицы: {r1}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2
Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
