In [1]:
import numpy as np


1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$



In [12]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3,-4, 2],
              [1, 6, 5],
              [0, 1, 0]])


print(f'Матрица A:\n{A}')

U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T
print(f'Матрица V:\n{V}')

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'Cписок диагональных элементов:\n{s}')

print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]
Cписок диагональных элементов:
[8.82486885 6.14060608 2.53271528]
Матрица D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]


In [15]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.00000000e+00  6.31672308e-17 -1.75301316e-16 -1.17939618e-16
  -8.57750402e-18]
 [ 6.31672308e-17  1.00000000e+00  8.26028228e-17 -5.17318224e-17
   3.82745166e-18]
 [-1.75301316e-16  8.26028228e-17  1.00000000e+00 -2.71839651e-16
  -9.89547134e-17]
 [-1.17939618e-16 -5.17318224e-17 -2.71839651e-16  1.00000000e+00
  -2.61324878e-17]
 [-8.57750402e-18  3.82745166e-18 -9.89547134e-17 -2.61324878e-17
   1.00000000e+00]]
[[ 1.00000000e+00  2.00000000e+00  5.69432293e-16]
 [ 1.03164637e-15 -2.16649373e-15  5.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  6.00000000e+00  5.00000000e+00]
 [-1.05854814e-16  1.00000000e+00  5.52894695e-17]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.