__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [2]:
import numpy as np

In [ ]:
# Задача 1

Ae1 = -1*e1 + 2*e2 = 2e2 - 1e1
Ae2 = -6*e1 +6*e2 = 6e2 - 6e1

In [ ]:
 Собственные значения

|[[-1-u, -6],[2, 6-u]]|=0
(-1-u)*(6-u) - 2*6 = 0
-6-6u+u+u**2 - 12 = 0
u**2-5*u-18 = 0
u1 = 2,5 + sqrt(97)/2
u2 = 2,5 - sqrt(97)/2

Подозреваю, что вручную посчитал что-то не то.

2e2 - 1e1 = e1 * (2,5 + sqrt(97)/2)
6e2 - 6e1 = e2 * (2,5 + sqrt(97)/2)

4e2 = 7e1 + sqrt(97)e1
-12e1 = sqrt(97)*e2 - 7e2



2e2 - 1e1 = e1 * (2,5 - sqrt(97)/2)
6e2 - 6e1 = e2 * (2,5 - sqrt(97)/2)

4e2 = 7e1 - sqrt(97)e1
12e1 = sqrt(97)*e2 + 7e2



In [3]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [ ]:
#  Попробовал подставить собственные значения в ручной расчет

2y - 1x = x * 2
6y - 6x = y * 2

у = 3х/2
x = 2y/3


2y - 1x = x * 3
6y - 6x = y * 3

y = 2x
x = y/2
# ничего не вышло

In [ ]:
# Задача 2

In [4]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


In [5]:
[[-1, 0], [0, -1]]*[2,-3] = u[2,-3]
-2-0=2u
0+3=-3u
u=-1
Решение есть, произвольный вектор является собственным.

[[-1, 0], [0, -1]]

In [ ]:
# Задача 3

In [8]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
x = np.array([1, 1])
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


In [11]:
a1 = a*x
a1

array([[ 1,  1],
       [-1,  3]])

In [ ]:
[[1, 1], [-1, 3]] = u * [1,1]

1+1=u
-1+3=u

u=2
Решение есть, вектор [1, 1] является собственным вектором оператора

In [ ]:
# Задча 4

In [12]:
a = np.array([[0, 3, 0], [3, 0, 0], [0,0,3]])
w, v = np.linalg.eig(a)
x = np.array([3, -3,-4])
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [13]:
a1 = a*x
a1

array([[  0,  -9,   0],
       [  9,   0,   0],
       [  0,   0, -12]])

In [ ]:
-9 = 3u
9 = -3u
-12 = -4u

u= -3
u= -3
u= 3

Решения нет, вектор [3, -3,-4] не является собственным