In [1]:
import numpy as np


1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$



In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3,-4, 2],
              [1, 6, 5],
              [0, 1, 0]])


print(f'Матрица A:\n{A}')

U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T
print(f'\nМатрица V:\n{V}')

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'\nCписок диагональных элементов:\n{s}')

print(f'\nМатрица D:\n{D}')
print(f'\nМатрица U:\n{U}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]

Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]

Cписок диагональных элементов:
[8.82486885 6.14060608 2.53271528]

Матрица D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]


In [13]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U).round())

X = np.dot(np.dot(U, D), V.T)
# Проведем проверку
print("\nПроверка:\n",X.round())

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0. -0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0. -0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]

Проверка:
 [[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [38]:
# а) норма Евклида

print("норма Евклида", np.linalg.norm(A, ord=2))


np.linalg.norm(A, ord=2).round() == D[0,0]
D[0,0]
#print("норма Евклида", np.linalg.norm(A, ord='nuc'))

норма Евклида 8.824868854820444


8.824868854820442

In [30]:
# б) норма Фробениуса

print("норма Фробениуса", np.linalg.norm(A, ord=None))

n = 0
for i in A:
    for j in i:
        n += j*j
print("норма Фробениуса - ручной алгоритм расчета", np.sqrt(n))


норма Фробениуса 11.045361017187261
норма Фробениуса - ручной алгоритм расчета 11.045361017187261


In [31]:

print("норма Фробениуса для D", np.linalg.norm(D, ord=None))



норма Фробениуса 11.045361017187261
